#! /bin/bash

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

# note: this script relies on `lib.d` files in minimized being generate
# they are generated by `../experiments/run.sh`

# ironkv
../experiments/build-verus.sh ../verus/sample-failure/
pushd ../verus/sample-failure/source/tools/minimize
rm -rf ./tmp
cargo run --release -- -s -d ./tmp ../../../../../experiments/broadcast-from-main/verified-ironkv/ironsht/src/lib.d > ironkv.log
popd
mv ../verus/sample-failure/source/tools/minimize/*.json ironkv/
mv ../verus/sample-failure/source/tools/minimize/ironkv.log ironkv/

# splinter
pushd ../verus/sample-failure/source/tools/minimize
rm -rf ./tmp
cargo run --release -- -s -d ./tmp ../../../../../experiments/broadcast-from-main/verified-betrfs/Splinter/src/lib.d > splinter.log
popd
mv ../verus/sample-failure/source/tools/minimize/*.json splinter/
mv ../verus/sample-failure/source/tools/minimize/splinter.log splinter/

# anvil
../experiments/build-verus.sh ../verus/sample-failure-anvil/
pushd ../verus/sample-failure-anvil/source/tools/minimize
rm -rf ./tmp
cargo run --release -- -s -d ./tmp ../../../../../experiments/broadcast-from-main/anvil/src/anvil.d > anvil.log
popd
mv ../verus/sample-failure-anvil/source/tools/minimize/*.json anvil/
mv ../verus/sample-failure-anvil/source/tools/minimize/anvil.log anvil/

# capybara
../experiments/build-verus.sh ../verus/sample-failure-capybara/
# copy deps_hack into src
cp -r ../experiments/broadcast-from-main/verified-storage/osdi25/capybaraKV/deps_hack ../experiments/broadcast-from-main/verified-storage/osdi25/capybaraKV/capybarakv/src/
pushd ../verus/sample-failure-capybara/source/tools/minimize
rm -rf ./tmp
cargo run --release -- -s -d ./tmp ../../../../../experiments/broadcast-from-main/verified-storage/osdi25/capybaraKV/capybarakv/src/lib.d > capybara.log
popd
mv ../verus/sample-failure-capybara/source/tools/minimize/*.json capybara/
mv ../verus/sample-failure-capybara/source/tools/minimize/capybara.log capybara/


